#! /bin/bash

# this script creates the latex file for figures generated by the plot_script.sh

if [ ! -d figure_tex ]
then
  mkdir figure_tex
fi

rm figure_tex/*



for region in $(cat ../regions/region_list.txt)
do

	number_locations=$(wc -l < ../regions/${region}/location_list.txt)
	

	for counter in $(seq 1 ${number_locations} )
	do
		location=$(awk -v line=${counter} --field-separator '\t' '{if (NR==line) {print $1}}' ../regions/${region}/location_list.txt)
		subregion=$(awk -v line=${counter} --field-separator '\t' '{if (NR==line) {print $2}}' ../regions/${region}/location_list.txt)

		if [ -d ../regions/${region}/${location} ]
		then

			subregion_space=$(echo ${subregion} | sed 's/_/ /g')
			location_space=$(echo ${location} | sed 's/_/ /g')

			if [ ! -f figure_tex/${subregion}.tex ]
			then
				cat << END_CAT > figure_tex/${subregion}.tex 
\subsection{${subregion_space}}

References for the data used in each location.

END_CAT


			fi

			plot=plots/${region}_${location}.pdf

			data_file="../regions/${region}/${location}/${location}.txt"

			# extract references


			awk --field-separator '\t'  '{if(NR > 1) print $16}' ${data_file} | sed 's/,/\n/g' > temp/references.txt

			sort temp/references.txt > temp/references2.txt

			awk 'BEGIN {last="FFF"; collect=""} {if ($1 != last) {if(collect == "") {collect=$1} else {collect=collect","$1}}; last = $1} END {print collect}' temp/references2.txt > temp/references3.txt



			cat << END_CAT >> figure_tex/${subregion}.tex 

${location_space}: \citet{$(cat temp/references3.txt)}

END_CAT


			# now make the file for the figures


			cat << END_CAT >> figure_tex/${subregion}_figures.tex 
\clearpage

\begin{figure}[t]
\includegraphics[width=12cm]{${plot}}
\caption{Paleo-sea level and comparison of six models for subregion ${subregion_space}, location ${location_space}.}
\label{fig:${location}}
\end{figure}

END_CAT

	
		fi

	done



done
