# The compiler
FC = gfortran

FCFLAGS2 = -g -fbacktrace -fbounds-check 
FCFLAGS = -O2 
OBFLAGS = -c


radiocarbon_statistics: radiocarbon_statistics.f90
	$(FC) -o radiocarbon_statistics $(FCFLAGS) radiocarbon_statistics.f90


